export const IPC = {
  samplesGet: 'samples:get',
  settingsGet: 'settings:get',
  settingsSet: 'settings:set',
  apiKeySet: 'apikey:set',
  apiKeyClear: 'apikey:clear',
  statusGet: 'status:get',
  capturePause: 'capture:pause',
  captureResume: 'capture:resume',
  captureOnce: 'capture:once',
  permissionRequest: 'permission:request',
  permissionOpen: 'permission:open',
  permissionHas: 'permission:has',
  permissionAccessibilityRequest: 'permission:accessibility:request',
  permissionAccessibilityOpen: 'permission:accessibility:open',
  dataDeleteAll: 'data:deleteAll',
  statusUpdate: 'status:update',
  settingsUpdate: 'settings:update',

  authSignIn: 'auth:signIn',
  authSignOut: 'auth:signOut',
  authSessionGet: 'auth:session:get',
  authSessionUpdate: 'auth:session:update',

  syncStatusGet: 'sync:status:get',
  syncStatusUpdate: 'sync:status:update',
  syncFlushNow: 'sync:flushNow',
  syncRetryFailed: 'sync:retryFailed',

  billingCheckout: 'billing:checkout',
  billingPortal: 'billing:portal',
  billingPlanGet: 'billing:plan:get',
  billingPlanUpdate: 'billing:plan:update',
} as const;
