export const IPC = {
  samplesGet: 'samples:get',
  settingsGet: 'settings:get',
  settingsSet: 'settings:set',
  apiKeySet: 'apikey:set',
  apiKeyClear: 'apikey:clear',
  statusGet: 'status:get',
  capturePause: 'capture:pause',
  captureResume: 'capture:resume',
  captureOnce: 'capture:once',
  permissionRequest: 'permission:request',
  permissionOpen: 'permission:open',
  permissionHas: 'permission:has',
  permissionAccessibilityRequest: 'permission:accessibility:request',
  permissionAccessibilityOpen: 'permission:accessibility:open',
  dataDeleteAll: 'data:deleteAll',
  statusUpdate: 'status:update',
  settingsUpdate: 'settings:update',
} as const;
